name: Monthly Maintenance

on:
  schedule:
    - cron: '0 0 1 * *' # Runs at midnight on the 1st of the month
  workflow_dispatch:

jobs:
  maintenance:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Cleanup
        run: python cleanup.py

      - name: Commit Maintenance
        run: |
          git config --local user.name "${{ github.actor }}"
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "chore: monthly archive cleanup" || exit 0
          git push
